services:
  db:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - $PWD/db_data:/data
      - $PWD/db_logs:/logs
      - $PWD/db_import:/var/lib/neo4j/import
    environment:
      - NEO4J_AUTH=neo4j/pizzapizza
    deploy:
      resources:
        limits:
          memory: 2.5g

  app:
    image: advdaba23:latest
    depends_on:
      - db
    volumes:
      - $PWD/app_logs:/logs
    deploy:
      resources:
        limits:
          memory: 2.5g